name: Daily Tieba Sign-In 2

on:
  workflow_dispatch:
  schedule:
    - cron: '10 16 * * *' # cron表达式，时区是UTC时间，我们是UTC+8小时,UTC 22:30 = 北京时间次日 06:30

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Random delay
        env:
          DELAY_MIN: 0
          DELAY_MAX: 60
        run: |
          stdbuf -oL -eL bash -c '
          DELAY_MIN="$1"
          DELAY_MAX="$2"
          RANDOM_DELAY=$(( RANDOM % (DELAY_MAX - DELAY_MIN + 1) + DELAY_MIN ))
          echo "========================================"
          echo "⏱️ 随机延迟: ${RANDOM_DELAY} 分钟后开始执行..."
          echo "========================================"
          if [ $RANDOM_DELAY -gt 0 ]; then
            #将分钟转换为秒，用于循环计算
            TOTAL=$(( RANDOM_DELAY * 60 ))
            ELAPSED=0
            # 每180秒打印一次进度，避免高频循环
            INTERVAL=180
            while [ "${ELAPSED}" -lt "${TOTAL}" ]; do
              # 剩余等待时长
              REM=$(( TOTAL - ELAPSED ))
              SLEEP_TIME=$(( REM < INTERVAL ? REM : INTERVAL ))
              sleep "${SLEEP_TIME}"
              ELAPSED=$(( ELAPSED + SLEEP_TIME ))

              ELAPSED_MIN=$(( ELAPSED / 60 ))
              REMAINING_MIN=$(( (TOTAL - ELAPSED) / 60 ))
              REMAINING_SEC=$(( (TOTAL - ELAPSED) % 60 ))
              echo "⏳ 已等待 ${ELAPSED_MIN} 分钟，剩余约 ${REMAINING_MIN} 分 ${REMAINING_SEC} 秒，⏱️ 总延迟: ${RANDOM_DELAY} 分钟..."
            done
          fi
          echo "✅ 延迟结束!"' bash "${DELAY_MIN}" "${DELAY_MAX}"

      - name: Run sign-in
        env:
          BDUSS: ${{ secrets.BDUSS2 }}
        run: python run.py

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
