name: Daily Tieba Sign-In 2

on:
  workflow_dispatch:
  schedule:
    - cron: '10 16 * * *' # cron表达式，时区是UTC时间，我们是UTC+8小时,UTC 22:30 = 北京时间次日 06:30

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Random delay - Calculate
        id: calc_step
        env:
          DELAY_MIN: 0
          DELAY_MAX: 60
        run: |
          RANDOM_DELAY=$(( RANDOM % (DELAY_MAX - DELAY_MIN + 1) + DELAY_MIN ))
          echo "========================================"
          echo "⏱️ 随机延迟: ${RANDOM_DELAY} 分钟后开始执行..."
          echo "========================================"
          echo "delay_time=${RANDOM_DELAY}" >> $GITHUB_OUTPUT

      - name: Random delay - Execute Sleep
        run: |
          sleep ${{ steps.calc_step.outputs.delay_time }}m
          
      - name: Run sign-in
        env:
          BDUSS: ${{ secrets.BDUSS2 }}
        run: python run.py

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
